# Generated by Django 4.2.2 on 2023-06-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency1', models.CharField(max_length=10)),
                ('currency2', models.CharField(max_length=10)),
                ('price1', models.IntegerField(default=0)),
                ('price2', models.IntegerField(default=0)),
            ],
        ),
    ]
