# Generated by Django 4.2.2 on 2023-06-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_transaction_amount_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_one',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_two',
            field=models.IntegerField(default=0),
        ),
    ]
